site_name: Vote Dallas

markdown_extensions:
  - attr_list
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

theme:
  name: material

extra_css:
  - css/site.css

extra:
  # analytics:
    # provider: google
    # property: G-LEGEFL2H8J
  generator: false
