site_name: Vote Dallas

markdown_extensions:
  - attr_list

theme:
  name: material

extra_css:
  - css/site.css

extra:
  analytics:
    provider: google
    property: G-LEGEFL2H8J
  generator: false
